---
- hosts: myhosts
  vars:
    ansible_ssh_private_key_file: /home/vladyslav/project/.vagrant/machines/default/virtualbox/private_key
  
  tasks:
    - name: Install Docker
      become: true
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      become: true
      service:
        name: docker
        state: started

    - name: Pull Nginx image
      become: true
      command: docker pull nginx:latest

    - name: Run Nginx container
      become: true
      command: docker run -d --name mynginx -p 80:80 nginx:latest

    - name: Display container details
      become: true
      shell: docker ps -a
      register: docker_ps_output

    - debug:
        var: docker_ps_output.stdout_lines

